name: Countdown to Tet Nguyen Dan

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  countdown:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Calculate countdown
      id: countdown
      run: |
        TODAY=$(date +%s)
        LUNAR_NEW_YEAR_DATE=$(date -d "2025-01-29" +%s)  
        SECONDS_LEFT=$(( LUNAR_NEW_YEAR_DATE - TODAY ))
        DAYS_LEFT=$(( SECONDS_LEFT / 86400 ) + 1)

        # if today is Lunar New Year
        if [ $SECONDS_LEFT -lt 86400 ] && [ $SECONDS_LEFT -ge 0 ]; then
          echo "is_lunar_new_year=true" >> $GITHUB_ENV
        else
          echo "is_lunar_new_year=false" >> $GITHUB_ENV
        fi
        echo "DAYS_LEFT=$DAYS_LEFT" >> $GITHUB_ENV

    - name: Update README.md with countdown
      run: |
        if [ "$is_lunar_new_year" = "true" ]; then
          sed -i "s/## 🎉 [0-9]\+ days left until Lunar New Year/# 🎉 HAPPY LUNAR NEW YEAR 🎆/" README.md
        else
          sed -i "s/## 🎉 [0-9]\+ days left until Lunar New Year/## 🎉 $DAYS_LEFT days left until Lunar New Year/" README.md
        fi
    - name: Commit countdown update
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add README.md
        git commit -m "Update countdown: $DAYS_LEFT days left until Lunar New Year"
        git push
